Python version of the Slack sample
autokitteh/samples pull request #82
Opened 2024-05-24 07:48 UTC by daabr

Related to - but does not fully resolve - ENG-879 and ENG-899.

Notes:
1. The usage of munch depends on https://github.com/autokitteh/autokitteh/pull/332
2. TODO in the code (bottom of both program files): ENG-802
3. Is it possible to have better handling of secrets? (i.e. initialize Slack client without exposing the bot token in the manifest or in the script's env vars)
4. UX reminder: https://github.com/autokitteh/autokitteh/pull/286

2024-05-26 15:32 UTC, tebeka commented
`munch` looks cool, but I prefer not to add it.

We'll need to support any package that we add to the default venv indefinitely for backward compatibility. That's why I think we should stick to parity with integration and maybe very selected few that are super popular (currently only PyYAML and requests). The user can install whatever they want to the environment if they want to work.

I don't think `munch` passes the threshold of making it to the default enviroment.

@daabr What is the reasoning for adding it to the default environment?

2024-05-26 16:25 UTC, tebeka requested changes

2024-05-26 16:25 UTC, tebeka commented on slack/program.py
> +    Args:
Let's discuss which version of Python documentation do we want to use: Sphinx, Google or numpy (see [here](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html))

Personally I'm used to numpy version, but I don't have a strong perference.

2024-05-26 16:25 UTC, tebeka commented on slack/program.py
> +    text = f"You mentioned me in {channel} and wrote: `{data.text}`"
```suggestion
    data = event["data"]
    slack = _slack_client()

    # Send messages in response to the event:
    # - A DM to the user who triggered the event
    # - Two messages to the channel "#slack-test"
    # See: https://slack.dev/python-slack-sdk/api-docs/slack_sdk/web/client.html#slack_sdk.web.client.WebClient.chat_postMessage
    text = f"You mentioned me in <#{channel}> and wrote: `{text}`".format(**data)
```

2024-05-26 16:25 UTC, tebeka commented on slack/program.py
> +    slack.chat_postMessage(channel=data.user, text=text)
Comment why channel is `data.user`

2024-05-26 16:25 UTC, tebeka commented on slack/program.py
> +    """https://api.slack.com/events/message
This URL doesn't explain what the handler does.

2024-05-26 16:25 UTC, tebeka commented on slack/program.py
> +    text %= (user, data.previous_message.text, data.message.text)
This uses old style formatting, keep it consistent and use new style or f-strings.

2024-05-26 16:25 UTC, tebeka commented on slack/program.py
> +    # in the AutoKitteh session's log, and finish.
Combine to a single line

2024-05-27 23:32 UTC, daabr commented on slack/README.md
> +- [Python web API reference](https://slack.dev/python-slack-sdk/api-docs/slack_sdk/web/client.html)
done

2024-05-27 23:35 UTC, daabr commented on slack/program.py
> +def _structify(event: dict, key: str = "") -> munch.Munch:
1. Indeed, let's discuss the typing topic offline
2. My rule of thumb is that if a function is shorter than the would-be docstring, and is trivial to understand, the docstring isn't needed; this is supported by Black's code checks which don't require a docstring for less than 5 LOC

2024-05-28 01:22 UTC, daabr commented on slack/program.py
> +import munch
I agree in general - I want Python samples to focus on the thing that they're demonstrating, i.e. integrations in existing samples (except PuRRR and future functional-goal-oriented samples).

However, event data is provided as a dictionary, and I don't consider that readable, so I'm forced to work around that with Munch. See my reply to your suggested change below.

For example, consider the unreadability of:

```python
slack.chat_update(channel=resp["channel"], ts=resp["ts"], text="Blah blah blah `{data[\"previous_message\"][\"text\"]}` blah `{data[\"message\"][\"text\"]}`")
```

...And rememeber that this is a **simple** example. Real-life usage is expected to be even more complex.

2024-05-28 19:37 UTC, daabr commented on slack/program.py
> +    text = f"You mentioned me in {channel} and wrote: `{data.text}`"
Resolved by https://github.com/autokitteh/autokitteh/pull/341

2024-05-29 16:14 UTC, daabr commented on slack/program.py
> +def _structify(event: dict, key: str = "") -> munch.Munch:
Even though I like type hinting a lot, I'm removing it for now. We'll rethink it if someone asks for it.

2024-05-30 14:53 UTC, tebeka commented on slack/program.py
> +import munch
> I still need to modify responses from the Slack SDK, but it's much simpler.

You mean one from the Python SDK? This is the experience Python users will have with the Slack SDK. Up to them what to do with it. I prefer to keep it as close to the SDK as possible.

2024-05-30 14:54 UTC, tebeka commented on slack/program.py
> +def _slack_client() -> slack_sdk.WebClient:
I prefer to call handler `on_event` or something like that, but go ahead and use `_`.

2024-05-30 14:56 UTC, tebeka commented on slack/program.py
> +    """https://api.slack.com/events/message
I meant comment like: `"event" comes from slack SDK, see https://api.slack.com/events/message for more information`

2024-05-30 15:58 UTC, daabr commented on slack/program.py
> +import munch
Agreed, but I'll do it in a separate PR.

2024-05-30 16:57 UTC, merged